default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  
  database: myapp
  username: holy
  password: 1234
  socket: /tmp/mysql.sock
test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  #hostname: 13.125.158.130
  database: kwaterdb
  username: deploy
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  # mariadb의 db socket의 위치가 다르다.
  #socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock
